name: Build & Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Frontend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: "./Frontend/package-lock.json"

      - name: Install dependencies
        run: npm ci
      - name: Build Angular files
        run: npm run build
      - name: Copy Angular files to Spring Boot static directory
        run: |
          cp -r ./dist/*  ../Backend/src/main/resources/static
  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Backend
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install packages
        run: yarn install --frozen-lockfile
          
      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Railway Up
        working-directory: ./Frontend
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}